version: '2'

services:
  mariadb: 
    build: ./mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234567890
      - MYSQL_DATABASE=bio
    volumes: 
      - "./container-data/mariadb/_PERSISTENT_/_var_lib_mysql:/var/lib/mysql"
      - "./container-data/mariadb/_PERSISTENT_/_etc_mysql:/etc/mysql"
      - "./container-data/mariadb/INITDB:/docker-entrypoint-initdb.d"
    command: ["mysqld"]
  phpmyadmin:
    image: nerelohw/docker-phpmyadmin
    ports:
      - "8081:80"
    links:
      - mariadb:db
    restart: always
    command: ["phpmyadmin"]
